# Generated by Django 4.0.3 on 2022-03-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_salary', models.IntegerField()),
                ('employee_age', models.IntegerField()),
            ],
        ),
    ]
